export const cardData = [
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
  {
    image: '/car1.jpg',
    carName: 'Toyota RAV4',
    mileage: '6.1',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car2.jpg',
    carName: 'Honda Civic',
    mileage: '5.5',
    people: 5,
    gasType: 'Petrol',
    price: 540,
    year: 2019,
  },
  {
    image: '/car3.jpg',
    carName: 'Ford Escape',
    mileage: '6.0',
    people: 4,
    gasType: 'Hybrid',
    price: 600,
    year: 2020,
  },
  {
    image: '/car4.jpg',
    carName: 'Nissan Altima',
    mileage: '5.8',
    people: 5,
    gasType: 'Petrol',
    price: 580,
    year: 2019,
  },
  {
    image: '/car5.jpg',
    carName: 'Chevrolet Malibu',
    mileage: '6.2',
    people: 4,
    gasType: 'Hybrid',
    price: 620,
    year: 2020,
  },
  {
    image: '/car6.jpg',
    carName: 'Toyota Corolla',
    mileage: '5.7',
    people: 5,
    gasType: 'Petrol',
    price: 560,
    year: 2019,
  },
];
